import "./globals.css";
import { Inter } from "next/font/google";
import { ApolloClient, InMemoryCache, createHttpLink } from "@apollo/client";
import { ApolloProvider } from "@apollo/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const link = createHttpLink({
    uri: "http://localhost:8080/query",
    credentials: "include",
  });

  const client = new ApolloClient({
    cache: new InMemoryCache(),
    link: link,
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProvider client={client}>{children}</ApolloProvider>
      </body>
    </html>
  );
}
